# Generated by Django 4.2.23 on 2025-06-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
    ]
